-- Reads lua/theme.lua (the single source of truth) and writes
-- out the derived, ready-to-use config files:
--
--     themes/foot.ini
--     themes/prompt.sh
--
-- Run from anywhere, e.g.:
--
--     lua lua/generate.lua

-- Locate project paths
local function script_dir()
    local src = debug.getinfo(1, "S").source:sub(2)
    return src:match("(.*/)") or "./"
end

local LUA_DIR = script_dir()
local ROOT_DIR = LUA_DIR .. "../"
local THEMES_DIR = ROOT_DIR .. "themes/"

local theme = dofile(LUA_DIR .. "theme.lua")

os.execute('mkdir -p "' .. THEMES_DIR .. '"')

-- Helpers
local function write_file(path, content)
    local f, err = io.open(path, "w")
    if not f then
        error(("could not write: %s: %s"):format(path, err))
    end
    f:write(content)
    f:close()
    print("wrote " .. path)
end

local function hex_to_rgb(hex)
    hex = hex:gsub("^#", "")
    local r = tonumber(hex:sub(1, 2), 16)
    local g = tonumber(hex:sub(3, 4), 16)
    local b = tonumber(hex:sub(5, 6), 16)
    return r, g, b
end

-- Themes/Foot.ini
local function build_foot_ini(t)
    local c = t.colors
    local out = {}

    local function line(s) out[#out + 1] = s end

    line("# ==============================================================")
    line("# Generated by lua/generate.lua from lua/theme.lua - DO NOT EDIT")
    line("# Palette: " .. t.name)
    line("# Regenerate with lua lua/generate.lua")
    line("# ==============================================================")
    line("")
    line("[main]")
    line(("font=%s:size=%d"):format(t.font.family, t.font.size))
    line(("pad=%dx%d"):format(t.layout.pad_x, t.layout.pad_y))
    line(("initial-window-size-chars=%dx%d"):format(t.layout.initial_cols, t.layout.initial_rows))
    line(("alpha=%.2f"):format(t.layout.opacity))
    line(("dpi-aware=%s"):format(t.foot_extras.dpi_aware and "yes" or "no"))
    line("# border_radius (" .. t.layout.border_radius .. "px) is not a foot")
    line("# feature — it's applied via a KWin window rule instead (see")
    line("# scripts/install.sh).")
    line("")
    line("[cursor]")
    line("style=" .. t.cursor.style)
    line("blink=" .. (t.cursor.blink and "yes" or "no"))
    line("color=" .. c.background .. " " .. c.cursor)
    line("")
    line("[mouse]")
    line("hide-when-typing=no")
    line("")
    line("[scrollback]")
    line("lines=" .. t.foot_extras.scrollback_lines)
    line("")
    line("[url]")
    line("launch=" .. t.foot_extras.url_launcher .. " ${url}")
    line("")
    line("[bell]")
    line("urgent=" .. (t.foot_extras.notify_on_bell and "yes" or "no"))
    line("notify=" .. (t.foot_extras.notify_on_bell and "yes" or "no"))
    line("")
    line("[colors]")
    line("background=" .. c.background)
    line("foreground=" .. c.foreground)
    line("selection-foreground=" .. c.background)
    line("selection-background=" .. c.foreground)
    line("")
    line("regular0=" .. c.black)
    line("regular1=" .. c.red)
    line("regular2=" .. c.green)
    line("regular3=" .. c.yellow)
    line("regular4=" .. c.blue)
    line("regular5=" .. c.magenta)
    line("regular6=" .. c.cyan)
    line("regular7=" .. c.white)
    line("")
    line("bright0=" .. c.bright_black)
    line("bright1=" .. c.bright_red)
    line("bright2=" .. c.bright_green)
    line("bright3=" .. c.bright_yellow)
    line("bright4=" .. c.bright_blue)
    line("bright5=" .. c.bright_magenta)
    line("bright6=" .. c.bright_cyan)
    line("bright7=" .. c.bright_white)
    line("")

    return table.concat(out, "\n")
end

-- themes/prompt.sh
local function build_prompt(t)
    local s = t.semantic
    local icons = t.icons
    local out = {}

    local function line(str) out[#out + 1] = str end

    line("#!/usr/bin/env bash")
    line("# ============================================================")
    line("# Generated by lua/generate.lua from lua/theme.lua — DO NOT EDIT")
    line("# Palette: " .. t.name)
    line("# Source this from ~/.bashrc:")
    line('#   source "' .. "$HOME/.config/EndeavourOS-Shell/prompt.sh" .. '"')
    line("# ============================================================")
    line("")
    line("__theme_git_segment() {")
    line("    local branch")
    line('    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)')
    line('    [ -z "$branch" ] && return')
    line("")
    line('    local dirty=""')
    line("    if ! git diff --quiet --ignore-submodules HEAD 2>/dev/null; then")
    line('        dirty=" ' .. icons.git_dirty .. '"')
    line("    fi")
    line("")
    line('    printf " \\e[38;2;125;207;255m' .. icons.git_branch .. ' %s%s\\e[0m" "$branch" "$dirty"')
    line("}")
    line("")
    line("__theme_exit_segment() {")
    line("    local code=$1")
    line('    if [ "$code" -eq 0 ]; then')
    line('        printf " \\e[38;2;158;206;106m' .. icons.exit_ok .. '\\e[0m"')
    line("    else")
    line('        printf " \\e[38;2;247;118;142m' .. icons.exit_fail .. ' %s\\e[0m" "$code"')
    line("    fi")
    line("}")
    line("")
    line("__theme_build_ps1() {")
    line("    local exit_code=$?")
    line('    printf "\\033]0;%%s@%%s:%%s\\007" "${USER}" "${HOSTNAME%%%%.*}" "${PWD/#$HOME/\\~}"')
    line("")
    line('    local path_str="\\[\\e[38;2;122;162;247m\\]' .. icons.folder .. ' \\w\\[\\e[0m\\]"')
    line('    local git_str=$(__theme_git_segment)')
    line('    local exit_str=$(__theme_exit_segment "$exit_code")')
    line("")
    line('    PS1="${path_str}${git_str}${exit_str}\\n\\[\\e[38;2;192;202;245m\\]' .. icons.prompt_arrow .. ' \\[\\e[0m\\]"')
    line("}")
    line("")
    line("PROMPT_COMMAND=__theme_build_ps1")

    return table.concat(out, "\n")
end

-- Helper for Bash
local function fix_bash_syntax(bash_src)
    return bash_src:gsub("\n    end\n", "\n    fi\n")
end

write_file(THEMES_DIR .. "foot.ini", build_foot_ini(theme))
write_file(THEMES_DIR .. "prompt.sh", fix_bash_syntax(build_prompt(theme)) .. "\n")

print("")
print("Done. Palette used: " .. theme.name)
